/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 BFB.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    NurbsPath: THREE.Mesh
    Sphere001: THREE.Mesh
    NurbsPath001: THREE.Mesh
    Sphere003: THREE.Mesh
    NurbsPath003: THREE.Mesh
    Sphere002: THREE.Mesh
    NurbsPath002: THREE.Mesh
    Sphere005: THREE.Mesh
    NurbsPath004: THREE.Mesh
    Sphere006: THREE.Mesh
    NurbsPath005: THREE.Mesh
    Plane004: THREE.Mesh
    Cube: THREE.Mesh
    Cube002: THREE.Mesh
    Cube001: THREE.Mesh
    Sphere004: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/BFB.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        scale={[0.532, 0.602, 0.532]}
      />
      <mesh
        geometry={nodes.NurbsPath.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.163}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials["Material.003"]}
        position={[0, 0.459, 0]}
        rotation={[0, 0, 0.274]}
        scale={[0.532, 0.602, 0.532]}
      />
      <mesh
        geometry={nodes.NurbsPath001.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        rotation={[0, 0, -1.297]}
        scale={0.163}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.532, -0.602, -0.532]}
      />
      <mesh
        geometry={nodes.NurbsPath003.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
        scale={-0.163}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials["Material.003"]}
        position={[0, 0.459, 0]}
        rotation={[Math.PI, 0, 0.274]}
        scale={[-0.532, -0.602, -0.532]}
      />
      <mesh
        geometry={nodes.NurbsPath002.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        rotation={[Math.PI, 0, -1.297]}
        scale={-0.163}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials["Material.001"]}
        position={[0, -0.205, 0]}
        rotation={[-0.027, -0.408, 0.755]}
        scale={[0.532, 0.602, 0.532]}
      />
      <mesh
        geometry={nodes.NurbsPath004.geometry}
        material={materials["Material.001"]}
        position={[0, -0.205, 0]}
        rotation={[-0.027, -0.408, -0.816]}
        scale={0.163}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials["Material.001"]}
        position={[0, -0.205, 0]}
        rotation={[3.115, -0.408, 0.755]}
        scale={[-0.532, -0.602, -0.532]}
      />
      <mesh
        geometry={nodes.NurbsPath005.geometry}
        material={materials["Material.001"]}
        position={[0, -0.205, 0]}
        rotation={[3.115, -0.408, -0.816]}
        scale={-0.163}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials["Material.002"]}
        position={[0, 0.459, 0]}
        rotation={[-3.135, -0.785, -3.137]}
        scale={1.562}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        scale={0.464}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        scale={0.464}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.002"]}
        position={[0, 0.459, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.464}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials["Material.001"]}
        position={[0, 0.459, 0]}
        scale={0.127}
      />
    </group>
  );
}

useGLTF.preload('/BFB.glb')
